### ISSUE TITLE
0.5.0 Hertz Issue

### ISSUE THREAD

**Issue by HorizonCode** [OpenTabletDriver/TabletDriverFilters#13]
When enabling the Devocub AntiChatter Interpolator, this trace is dumped.
```
Jan 19 22:50:26 horizon-linux otd[19027]: Unhandled exception. System.MissingMethodException: Method not found: 'Single OpenTabletDriver.Plugin.Tablet.Interpolator.Interpolator.get_Hertz()'.
--
2 | Jan 19 22:50:26 horizon-linux otd[19027]:    at TabletDriverFilters.Devocub.AntiChatter.get_TimerInterval()
3 | Jan 19 22:50:26 horizon-linux otd[19027]:    at TabletDriverFilters.Devocub.AntiChatter.Filter(Vector2 calcTarget)
4 | Jan 19 22:50:26 horizon-linux otd[19027]:    at TabletDriverFilters.Devocub.AntiChatter.Interpolate()
5 | Jan 19 22:50:26 horizon-linux otd[19027]:    at OpenTabletDriver.Plugin.Tablet.Interpolator.Interpolator.InterpolateHook() in /home/horizoncode/.cache/yay/opentabletdriver-git/src/OpenTabletDriver/OpenTabletDriver.Plugin/Tablet/Interpolator/Interpolator.cs:line 99
6 | Jan 19 22:50:26 horizon-linux otd[19027]:    at OpenTabletDriver.Desktop.Interop.Timer.LinuxTimer.Callback(SigVal _) in /home/horizoncode/.cache/yay/opentabletdriver-git/src/OpenTabletDriver/OpenTabletDriver.Desktop/Interop/Timer/LinuxTimer.cs:line 108
```

OpenTabletDriver Build:
`opentabletdriver-git v0.5.0.r0.g80cf89e-1`

**Comment by Mrcubix** [comment]
known issue, will be fixed when plugin update happen

**Comment by X9VoiD** [comment]
Already fixed on latest master, New release will come in sync with OTD 0.5.1 hotfix.
