### ISSUE TITLE
Unable to load HawkuFilters plugin on OTD v0.6.0.4

### ISSUE THREAD

**Issue by Wieku** [OpenTabletDriver/TabletDriverFilters#24]
```
[Plugin:Warning]	Plugin 'HawkuFilters, Version=1.0.0.0' can't be loaded and is likely out of date. (HResult: 0x80131602)
Unable to load one or more of the requested types.
Could not load type 'OpenTabletDriver.Plugin.Tablet.Interpolator.Interpolator' from assembly 'OpenTabletDriver.Plugin, Version=0.6.0.4, Culture=neutral, PublicKeyToken=null'.
Could not load type 'OpenTabletDriver.Plugin.Tablet.IFilter' from assembly 'OpenTabletDriver.Plugin, Version=0.6.0.4, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at OpenTabletDriver.Desktop.Reflection.PluginManager.IsLoadable(Assembly asm)
```

**Comment by jamesbt365** [comment]
assuming windows because you didn't say.

remove `%localappdata\OpenTabletDriver\Plugins`, `temp` if its there and `cache`. Make sure you close otd properly, reopen it and reinstall the plugin.

**Comment by Wieku** [comment]
Oh, I was reinstalling the plugin using manager and manually, using repository and github release. Clearing temp and cache worked, thanks.
